language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: VUT6L2ptXDovGX9/koS1DtNqKD865O3FhkqNXz3xqnKSaavo3CH0d+XWdUjIwZYBB0vnk+hjtmMqZE4xXyXcQcMk0M8ENBDN1myEdKZKJouRtijTWbyYWH2IKNHTVQW8+0leUg+P6rSaDPpxejNm2kHkq/j6BSzS84z/wBPCI136tmRV09iQD4csfaT/QrzpmGTFQSdrvvMxyGIvu8XqxiLwPqdHrAkwFD7vDgr59jKGWiLDst3cZb5Lnt5Fm+VfGy5U+GjPliVU5U6Y2PEsLPK3LWMNzpMVKUblOwD4TMR6iDsr6ilcMzAVuZxpiazLseeLLKtcSpoBHcH8jw56DBD3G/V47XwVipIcmS5kKeLuCkuU8svkzfI0MEhVoQ58qqRIc/hb6s8oOY9YxpPIFzlkR9IXSyDsBQDdTCNjUsRT2GZGQ1JGt8thYHfEWrGffdRLb9MCff99yscl/pEnPRwQs5Bt1kMC1tr6MzeBQILqNQVN3LRKzqTsuPKpuyCwWemsY0q7n95ChNPSBP1LntYzrrh7J94QxuRmDTKKGXIs5L05YohN6vh7S7UEP0MQsHo2vXg1c7KGOwfrIugkRTcYqu3zOZgrGof1F4pJErYNO+F7l1cy3lsU9Tq2VdS/RTauRA0XaQex9YWXkHtVmHeF1R9Lb5D5n6+P43wjhLg=
  app: shopping-list-test
  on:
    repo: Blubagoo/shopping-list-test
