language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: eAny/eL2cvC6GVdeSXDeUwJSHuQ8v6RubNyjR4lIGuBKtTGa/+j8Ezr2EAac+Hku81+2i3AsQMQCFDkZkh5zlZkzraMJPuRXpc5OKra+IpVHH2YHfadEKb6404lv6IrNmK1fi/59E3uSS0oTaD+n6FBPuvu1aaYX/osPI1K59QOsLlV2ARP/wk2VZdAN4B2Y9iZ1ct7ge8rXenDm2BYCoFkYWv+2oxCY3ogvH3vYrGkO87NvtQJWp0jo8h0r46bumFOjYDBlqh3dUXGMQRyrMx2aukEh2IK8DcJm0c5qPDzWytPVNlY8gy4/UQrB7aKuKBVwzVsQ3VoGUiAQ/ETJ1CSLfgecnBS2yfl4ZUrqI8l5QiSqrQNuVDdkYlGhFzYXKHOgPGU+8+UjnCfw9HrcBpH+InxdXMhMg1nPw7fuzS0W9T59cN9iJpRTD0pUdHhUpi4vl+39STx6O9xMbiApv3dnAnvYI+UPrLdx10aAUGrsrm4imblIkuPs7w6LInXGXAU5VMgnPWfMOqSvXdikVgJKDH0C325nSeM0h9vm9bRIJ9Vf5LmD3iJc0uJMSAak//yFIIuCQAHKy1Q/n6U/dVqdFjydwC9wAd6DHggPXKNFI/V4a94Zc1iaLlNCOy4jGq/vBgznCCD+E/0aM2JroATj7/KJEVA2nIxrXHrNUDc=
  app: shopping-list-test
  on:
    repo: Blubagoo/shopping-list-test
